spring.application.name=projectmanagement

spring.profiles.active=local

# JPA/Hibernate Common Config
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Config (Secret Key is Base64 encoded)
jwt.secret=cMzFwR3VuZ3NlY3VyaXR5and0c2VjcmV0a2V5Zm9ycHJvamVjdG1hbmFnZW1lbnRhcHB2YWx1ZQ==
jwt.expiration-time=1800000
